name: release-flow

# https://help.github.com/en/articles/events-that-trigger-workflows#release-event-release
# on: release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"

jobs:
#  build-macOS:
#    runs-on: macOS-latest
#
#    steps:
#      - name: Get tag
#        id: tag
#        uses: dawidd6/action-get-tag@v1
#      - uses: actions/checkout@v2
#      - uses: actions-rs/toolchain@v1
#        with:
#          toolchain: stable
#          override: true
#      - name: Build and release
#        run: |
#          cargo build --release
#          mkdir -p mini_jam_72.app/Contents/MacOS
#          cp -r assets/ mini_jam_72.app/Contents/MacOS/
#          cp target/release/mini_jam_72 mini_jam_72.app/Contents/MacOS/
#          strip mini_jam_72.app/Contents/MacOS/mini_jam_72
#          hdiutil create -fs HFS+ -volname "mini_jam_72" -srcfolder mini_jam_72.app mini_jam_72.dmg
#      - name: Upload binaries to release
#        uses: svenstaro/upload-release-action@v2
#        with:
#          repo_token: ${{ secrets.GITHUB_TOKEN }}
#          file: mini_jam_72.dmg
#          asset_name: mini_jam_72_macOS_${{ steps.tag.outputs.tag }}.dmg
#          tag: ${{ github.ref }}
#          overwrite: true

  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Get tag
        id: tag
        uses: dawidd6/action-get-tag@v1
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Install Dependencies
        run: sudo apt-get install pkg-config libx11-dev libasound2-dev libudev-dev
      - name: Build and release
        run: |
          cargo build --release
          strip target/release/mini_jam_72
      - name: Prepare assets
        run: |
          mkdir target/release/assets && cp -r assets target/release/assets
      - uses: papeloto/action-zip@v1
        with:
          files: target/release/assets/ target/release/mini_jam_72
          dest: mini_jam_72_linux.zip
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: mini_jam_72_linux.zip
          asset_name: mini_jam_72_linux_${{ steps.tag.outputs.tag }}.zip
          tag: ${{ github.ref }}
          overwrite: true

  build-windows:
    runs-on: windows-latest

    steps:
      - name: Get tag
        id: tag
        uses: dawidd6/action-get-tag@v1
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Build and release
        run: |
          cargo build --release
      - name: Prepare assets
        run: |
          mkdir target/release/assets && cp -r assets target/release/assets
      - uses: papeloto/action-zip@v1
        with:
          files: target/release/assets/ target/release/mini_jam_72.exe
          dest: mini_jam_72_windows.zip
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: mini_jam_72_windows.zip
          asset_name: mini_jam_72_windows_${{ steps.tag.outputs.tag }}.zip
          tag: ${{ github.ref }}
          overwrite: true
